/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Day
         * @description Everything for one day.
         */
        get: operations["get_day_days__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Days
         * @description Everything for each day in a range. Days with no data are still included.
         */
        get: operations["get_days_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fitness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fitness
         * @description Today by default. Pass date for one day, or start and end for a range.
         */
        get: operations["get_fitness_fitness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sleep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sleep
         * @description Only nights that have data.
         */
        get: operations["get_sleep_sleep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Todos
         * @description Today by default. Pass date for one day, or start and end for a range.
         */
        get: operations["get_todos_todos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trades
         * @description Journal entries plus wins, losses and win rate. All time unless a range is given.
         */
        get: operations["get_trades_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/chess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chess
         * @description chess.com: rating, record, colour and opening stats over every saved game, plus a page of games.
         */
        get: operations["get_chess_games_chess_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Goals
         * @description My targets (steps, calories, macros, sleep, workouts per week). Defaults until first saved.
         */
        get: operations["get_goals_goals_get"];
        /**
         * Put Goals
         * @description Replaces my targets. A field set to null switches that goal off.
         */
        put: operations["put_goals_goals_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Streaks
         * @description Food logging streak in days and gym streak in weeks, as of today.
         */
        get: operations["get_streaks_streaks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Status
         * @description The latest sync for each source.
         */
        get: operations["sync_status_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Health
         * @description Receives Health Auto Export's REST API automation.
         */
        post: operations["ingest_health_ingest_health_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/notion/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Notion Now
         * @description Pulls the to do list and trading journal from Notion right now.
         */
        post: operations["sync_notion_now_ingest_notion_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/food-suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Food Suggestion
         * @description Runs the evening food check now, instead of waiting for the scheduled time.
         */
        post: operations["trigger_food_suggestion_alerts_food_suggestion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/weekly-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Weekly Report
         * @description Builds and sends this week's report now.
         */
        post: operations["trigger_weekly_report_alerts_weekly_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/notion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notion Webhook */
        post: operations["notion_webhook_webhooks_notion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Chess */
        Chess: {
            /** Time Class */
            time_class: string;
            /**
             * @default {
             *       "games": 0,
             *       "wins": 0,
             *       "losses": 0,
             *       "draws": 0,
             *       "abandoned": 0
             *     }
             */
            summary: components["schemas"]["ChessSummary"];
            /**
             * @default {
             *       "games": 0,
             *       "wins": 0,
             *       "losses": 0,
             *       "draws": 0
             *     }
             */
            white: components["schemas"]["ChessRecord"];
            /**
             * @default {
             *       "games": 0,
             *       "wins": 0,
             *       "losses": 0,
             *       "draws": 0
             *     }
             */
            black: components["schemas"]["ChessRecord"];
            /**
             * Openings
             * @default []
             */
            openings: components["schemas"]["ChessOpening"][];
            /**
             * Rating History
             * @default []
             */
            rating_history: components["schemas"]["ChessRatingPoint"][];
            /**
             * Total Games
             * @default 0
             */
            total_games: number;
            /**
             * Games
             * @default []
             */
            games: components["schemas"]["ChessGameOut"][];
        };
        /** ChessGameOut */
        ChessGameOut: {
            /** Uuid */
            uuid: string;
            /** Url */
            url: string;
            /**
             * Ended At
             * Format: date-time
             */
            ended_at: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Time Class */
            time_class: string;
            /** Time Control */
            time_control: string;
            /** Rated */
            rated: boolean;
            /** Color */
            color: string;
            /** Rating */
            rating: number;
            /** Rating Change */
            rating_change?: number | null;
            /** Opponent */
            opponent: string;
            /** Opponent Rating */
            opponent_rating?: number | null;
            /** Result */
            result: string;
            /** Opponent Result */
            opponent_result: string;
            /** Outcome */
            outcome: string;
            /** Abandoned */
            abandoned: boolean;
            /** Opening */
            opening?: string | null;
            /** Eco */
            eco?: string | null;
        };
        /** ChessOpening */
        ChessOpening: {
            /**
             * Games
             * @default 0
             */
            games: number;
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Draws
             * @default 0
             */
            draws: number;
            /** Win Rate */
            win_rate?: number | null;
            /** Opening */
            opening: string;
        };
        /** ChessRatingPoint */
        ChessRatingPoint: {
            /**
             * Ended At
             * Format: date-time
             */
            ended_at: string;
            /** Rating */
            rating: number;
        };
        /**
         * ChessRecord
         * @description Games that ended normally. Abandoned games are listed in the history but not counted here.
         */
        ChessRecord: {
            /**
             * Games
             * @default 0
             */
            games: number;
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Draws
             * @default 0
             */
            draws: number;
            /** Win Rate */
            win_rate?: number | null;
        };
        /** ChessSummary */
        ChessSummary: {
            /**
             * Games
             * @default 0
             */
            games: number;
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Draws
             * @default 0
             */
            draws: number;
            /** Win Rate */
            win_rate?: number | null;
            /** Rating */
            rating?: number | null;
            /** Best Rating */
            best_rating?: number | null;
            /** Best Rating Date */
            best_rating_date?: string | null;
            /**
             * Abandoned
             * @default 0
             */
            abandoned: number;
        };
        /** Day */
        Day: {
            /**
             * Date
             * Format: date
             */
            date: string;
            fitness: components["schemas"]["Fitness"];
            sleep?: components["schemas"]["SleepOut"] | null;
            todo: components["schemas"]["TodoDay"];
            hobby: components["schemas"]["Hobby"];
        };
        /** Exercise */
        Exercise: {
            /** Name */
            name: string;
            /** Sets */
            sets?: number | null;
            /** Reps */
            reps?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** Fitness */
        Fitness: {
            /** Calories In */
            calories_in?: number | null;
            /** Calories Out */
            calories_out?: number | null;
            /** Active Calories */
            active_calories?: number | null;
            /** Basal Calories */
            basal_calories?: number | null;
            /** Steps */
            steps?: number | null;
            /** @default {} */
            macros: components["schemas"]["Macros"];
            heart_rate?: components["schemas"]["HeartRate"] | null;
            /**
             * Workouts
             * @default []
             */
            workouts: components["schemas"]["WorkoutOut"][];
        };
        /** FitnessDay */
        FitnessDay: {
            /** Calories In */
            calories_in?: number | null;
            /** Calories Out */
            calories_out?: number | null;
            /** Active Calories */
            active_calories?: number | null;
            /** Basal Calories */
            basal_calories?: number | null;
            /** Steps */
            steps?: number | null;
            /** @default {} */
            macros: components["schemas"]["Macros"];
            heart_rate?: components["schemas"]["HeartRate"] | null;
            /**
             * Workouts
             * @default []
             */
            workouts: components["schemas"]["WorkoutOut"][];
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** FoodStreak */
        FoodStreak: {
            /** Current */
            current: number;
            /** Best */
            best: number;
            /** Logged Today */
            logged_today: boolean;
        };
        /**
         * GoalsIn
         * @description My targets. None switches a goal off.
         */
        GoalsIn: {
            /** Steps */
            steps?: number | null;
            /** Calories In */
            calories_in?: number | null;
            /** Protein G */
            protein_g?: number | null;
            /** Carbs G */
            carbs_g?: number | null;
            /** Fat G */
            fat_g?: number | null;
            /** Sleep Hours */
            sleep_hours?: number | null;
            /** Workouts Per Week */
            workouts_per_week?: number | null;
        };
        /** GymStreak */
        GymStreak: {
            /** Current */
            current: number;
            /** Best */
            best: number;
            /** This Week */
            this_week: number;
            /** Target */
            target?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartRate */
        HeartRate: {
            /** Resting */
            resting?: number | null;
            /** Avg */
            avg?: number | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /**
             * Intervals
             * @default []
             */
            intervals: components["schemas"]["HeartRateInterval"][];
        };
        /** HeartRateInterval */
        HeartRateInterval: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
        /** Hobby */
        Hobby: {
            /**
             * @default {
             *       "trades": [],
             *       "summary": {
             *         "breakeven": 0,
             *         "losses": 0,
             *         "wins": 0
             *       }
             *     }
             */
            trading: components["schemas"]["Trading"];
        };
        /** Macros */
        Macros: {
            /** Protein G */
            protein_g?: number | null;
            /** Carbs G */
            carbs_g?: number | null;
            /** Fat G */
            fat_g?: number | null;
        };
        /** SleepDay */
        SleepDay: {
            /** Bedtime */
            bedtime?: string | null;
            /** Wake Time */
            wake_time?: string | null;
            /** Total Min */
            total_min?: number | null;
            /** Deep Min */
            deep_min?: number | null;
            /** Rem Min */
            rem_min?: number | null;
            /** Core Min */
            core_min?: number | null;
            /** Awake Min */
            awake_min?: number | null;
            heart_rate?: components["schemas"]["SleepHeartRate"] | null;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** SleepHeartRate */
        SleepHeartRate: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /**
             * Intervals
             * @default []
             */
            intervals: components["schemas"]["HeartRateInterval"][];
        };
        /** SleepOut */
        SleepOut: {
            /** Bedtime */
            bedtime?: string | null;
            /** Wake Time */
            wake_time?: string | null;
            /** Total Min */
            total_min?: number | null;
            /** Deep Min */
            deep_min?: number | null;
            /** Rem Min */
            rem_min?: number | null;
            /** Core Min */
            core_min?: number | null;
            /** Awake Min */
            awake_min?: number | null;
            heart_rate?: components["schemas"]["SleepHeartRate"] | null;
        };
        /** Streaks */
        Streaks: {
            food: components["schemas"]["FoodStreak"];
            gym: components["schemas"]["GymStreak"];
        };
        /** SyncStatus */
        SyncStatus: {
            /** Source */
            source: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Records */
            records: number;
            /** Error */
            error?: string | null;
        };
        /** TaskOut */
        TaskOut: {
            /** Title */
            title: string;
            /** Done */
            done: boolean;
        };
        /** TodoDay */
        TodoDay: {
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskOut"][];
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** TodoDayOut */
        TodoDayOut: {
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskOut"][];
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** TradeOut */
        TradeOut: {
            /** Date */
            date?: string | null;
            /** Entry */
            entry?: string | null;
            /** Result */
            result?: string | null;
            /** Actual Rr */
            actual_rr?: number | null;
            /** Intended Rr */
            intended_rr?: number | null;
            /** Trade Quality */
            trade_quality?: string | null;
            /** Followed Rules */
            followed_rules?: boolean | null;
            /** Bias Correct */
            bias_correct?: string | null;
            /** Time Of Entry */
            time_of_entry?: string | null;
            /** Emotion */
            emotion?: string | null;
            /** Execution */
            execution?: string | null;
            /** Note */
            note?: string | null;
        };
        /** Trading */
        Trading: {
            /**
             * Trades
             * @default []
             */
            trades: components["schemas"]["TradeOut"][];
            /**
             * @default {
             *       "wins": 0,
             *       "losses": 0,
             *       "breakeven": 0
             *     }
             */
            summary: components["schemas"]["TradingSummary"];
        };
        /** TradingSummary */
        TradingSummary: {
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Breakeven
             * @default 0
             */
            breakeven: number;
            /** Win Rate */
            win_rate?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkoutHeartRate */
        WorkoutHeartRate: {
            /** Min */
            min?: number | null;
            /** Avg */
            avg?: number | null;
            /** Max */
            max?: number | null;
        };
        /** WorkoutOut */
        WorkoutOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Duration Min */
            duration_min: number;
            /** Calories */
            calories?: number | null;
            heart_rate?: components["schemas"]["WorkoutHeartRate"] | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["Exercise"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_day_days__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Day"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_days_days_get: {
        parameters: {
            query?: {
                /** @description First day, YYYY-MM-DD. Defaults to 6 days before end. */
                start?: string | null;
                /** @description Last day, YYYY-MM-DD. Defaults to today. */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Day"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fitness_fitness_get: {
        parameters: {
            query?: {
                /** @description One day, YYYY-MM-DD. Defaults to today. */
                date?: string | null;
                /** @description First day of a range, YYYY-MM-DD. Use with end. */
                start?: string | null;
                /** @description Last day of a range, YYYY-MM-DD. Use with start. */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitnessDay"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sleep_sleep_get: {
        parameters: {
            query?: {
                /** @description One day, YYYY-MM-DD. Defaults to today. */
                date?: string | null;
                /** @description First day of a range, YYYY-MM-DD. Use with end. */
                start?: string | null;
                /** @description Last day of a range, YYYY-MM-DD. Use with start. */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SleepDay"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_todos_todos_get: {
        parameters: {
            query?: {
                /** @description One day, YYYY-MM-DD. Defaults to today. */
                date?: string | null;
                /** @description First day of a range, YYYY-MM-DD. Use with end. */
                start?: string | null;
                /** @description Last day of a range, YYYY-MM-DD. Use with start. */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoDayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trades_trades_get: {
        parameters: {
            query?: {
                /** @description First day, YYYY-MM-DD. Leave out for all time. */
                start?: string | null;
                /** @description Last day, YYYY-MM-DD. Leave out for all time. */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trading"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chess_games_chess_get: {
        parameters: {
            query?: {
                /** @description Which kind of game */
                time_class?: string;
                /** @description Games per page */
                limit?: number;
                /** @description Games to skip, newest first */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chess"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goals_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalsIn"];
                };
            };
        };
    };
    put_goals_goals_put: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalsIn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_streaks_streaks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Streaks"];
                };
            };
        };
    };
    sync_status_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"][];
                };
            };
        };
    };
    ingest_health_ingest_health_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_notion_now_ingest_notion_sync_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_food_suggestion_alerts_food_suggestion_post: {
        parameters: {
            query?: {
                /** @description Work out what would be sent, but send nothing */
                dry_run?: boolean;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_weekly_report_alerts_weekly_report_post: {
        parameters: {
            query?: {
                /** @description Work out what would be sent, but send nothing */
                dry_run?: boolean;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notion_webhook_webhooks_notion_post: {
        parameters: {
            query?: never;
            header?: {
                "x-notion-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
