"""initial tables

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 07:22:49.330256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_fitness',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories_in', sa.Float(), nullable=True),
    sa.Column('active_calories', sa.Float(), nullable=True),
    sa.Column('basal_calories', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('heart_rate_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resting', sa.Float(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_payloads_received_at'), 'raw_payloads', ['received_at'], unique=False)
    op.create_index(op.f('ix_raw_payloads_source'), 'raw_payloads', ['source'], unique=False)
    op.create_table('sleep',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bedtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wake_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_min', sa.Float(), nullable=True),
    sa.Column('deep_min', sa.Float(), nullable=True),
    sa.Column('rem_min', sa.Float(), nullable=True),
    sa.Column('core_min', sa.Float(), nullable=True),
    sa.Column('awake_min', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_source'), 'sync_log', ['source'], unique=False)
    op.create_index(op.f('ix_sync_log_started_at'), 'sync_log', ['started_at'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=64), nullable=False),
    sa.Column('notion_database_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion_page_id')
    )
    op.create_index(op.f('ix_todos_date'), 'todos', ['date'], unique=False)
    op.create_index(op.f('ix_todos_notion_database_id'), 'todos', ['notion_database_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entry', sa.String(length=500), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('actual_rr', sa.Float(), nullable=True),
    sa.Column('intended_rr', sa.Float(), nullable=True),
    sa.Column('trade_quality', sa.String(length=20), nullable=True),
    sa.Column('followed_rules', sa.Boolean(), nullable=True),
    sa.Column('bias_correct', sa.String(length=20), nullable=True),
    sa.Column('time_of_entry', sa.String(length=50), nullable=True),
    sa.Column('emotion', sa.Text(), nullable=True),
    sa.Column('execution', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion_page_id')
    )
    op.create_index(op.f('ix_trades_date'), 'trades', ['date'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_workouts_date'), 'workouts', ['date'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('notion_page_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion_page_id')
    )
    op.create_index(op.f('ix_workout_exercises_workout_id'), 'workout_exercises', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercises_workout_id'), table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_workouts_date'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_trades_date'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_todos_notion_database_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_date'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_sync_log_started_at'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_source'), table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_table('sleep')
    op.drop_index(op.f('ix_raw_payloads_source'), table_name='raw_payloads')
    op.drop_index(op.f('ix_raw_payloads_received_at'), table_name='raw_payloads')
    op.drop_table('raw_payloads')
    op.drop_table('heart_rate_daily')
    op.drop_table('daily_fitness')
    # ### end Alembic commands ###
